spring:
  application:
    name: eureka-provider #微服务调用名称
  cloud:
    config:
      label: master
      profile: t1
      uri: http://localhost:8782/
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/