spring:
  application:
    name: eureka-config #微服务调用名称
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/yun6713/springcloud01.git
          search-paths: config
server:
  port: 8782
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/