spring:
  application:
    name: eureka-consumer #微服务调用名称
server:
  port: 8772
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      feign-name: lalala
  hystrix:
    enabled: true #feign开启断路器
  