spring:
  application:
    name: eureka-zuul
server:
  port: 8781
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#zuul:
#  routes:
#    test: 
#      path: /test
#      service-id: /consumer/test