spring: 
  application:
    name: eureka-server
server: 
  port: 8761
eureka: 
  instance:
    hostname: localhost
  client: 
    register-with-eureka: false #eureka server
    fetch-registry: false #eureka server
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    